openapi: 3.0.0
tags:
  - name: Events
    description: Event listing and details endpoints

paths:
  /api/events:
    get:
      tags:
        - Events
      summary: Get all events
      description: Returns a list of all active events
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/EventSummary'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security: []

  /api/events/{id}:
    get:
      tags:
        - Events
      summary: Get event by ID
      description: Returns detailed information for a specific event
      parameters:
        - name: id
          in: path
          description: ID of the event to retrieve
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    $ref: '#/components/schemas/EventDetail'
        '404':
          description: Event not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security: []

  /api/events/{id}/availability:
    get:
      tags:
        - Events
      summary: Check event seat availability
      description: Returns the number of available seats for a specific event
      parameters:
        - name: id
          in: path
          description: ID of the event to check
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      eventId:
                        type: integer
                        example: 1
                      capacity:
                        type: integer
                        example: 500
                      registered:
                        type: integer
                        example: 230
                      available:
                        type: integer
                        example: 270
        '404':
          description: Event not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security: []

components:
  schemas:
    EventSummary:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: UNMA Annual Conference 2025
        description:
          type: string
          example: Join us for the annual UNMA conference featuring keynote speakers and networking opportunities.
        date:
          type: string
          format: date-time
          example: 2025-06-15T09:00:00Z
        location:
          type: string
          example: Grand Hotel, New York
        price:
          type: number
          format: float
          example: 299.99
        capacity:
          type: integer
          example: 500
        registeredCount:
          type: integer
          example: 230
        image:
          type: string
          example: https://example.com/event1.jpg
        isActive:
          type: boolean
          example: true
          
    EventDetail:
      allOf:
        - $ref: '#/components/schemas/EventSummary'
        - type: object
          properties:
            agenda:
              type: array
              items:
                type: object
                properties:
                  time:
                    type: string
                    example: 09:00 AM
                  title:
                    type: string
                    example: Registration & Breakfast
            speakers:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                    example: Dr. Jane Smith
                  bio:
                    type: string
                    example: Leading expert in the field
                  image:
                    type: string
                    example: https://example.com/speaker1.jpg
                    
    Error:
      type: object
      properties:
        status:
          type: string
          example: error
        message:
          type: string
          example: Internal server error 